name: 'redoc-cli'
description: 'Lets you use redoc-cli for generating REST API docs of your OpenAPI/Swagger documents.'
author: 'DeltaLaboratory <delta@deltalab.dev>'
branding:
  icon: 'book'
  color: 'green'
inputs:
  args:
    description: 'The arguments to pass over to redoc-cli'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}
